apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: target-custom-minimal-notebook
  namespace: redhat-ods-applications
spec:
  source:
    type: Git
    git:
      uri: https://github.com/butler54/rhoai-custom-image.git
    contextDir: helm
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Containerfile
      from:
        kind: ImageStreamTag  
        name: source-minimal-notebook:latest
  output:
    to:
      kind: ImageStreamTag
      name: target-custom-minimal-notebook:latest
  triggers:
  - type: ImageChange
  - type: ConfigChange