apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: custom-image-build
  namespace: redhat-ods-applications
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.gitRepository }}
    contextDir: helm
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Containerfile
      from:
        kind: ImageStreamTag  
        name: source-custom-stream:latest
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.targetImageName }}-stream:latest
  triggers:
  - type: ImageChange
  - type: ConfigChange