# Proxy image stream to flatten the stream to the 'latest' tag.
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: source-custom-stream
  namespace: redhat-ods-applications
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: ImageStreamTag  
      namespace: redhat-ods-applications
      name: "{{ .Values.sourceImageName }}:{{ .Values.sourceImageTag }}"
    referencePolicy:
      type: Source
