apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: source-cuda-notebook
  namespace: redhat-ods-applications
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: ImageStreamTag  
      namespace: redhat-ods-applications
      name: s2i-minimal-notebook:2024.1
    referencePolicy:
      type: Source
