apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.targetImageName }}-stream
  namespace: redhat-ods-applications
  annotations:
    #opendatahub.io/notebook-image-creator: "cluster-admin"
    opendatahub.io/notebook-image-desc: {{ .Values.targetImageDesc }}
    opendatahub.io/notebook-image-name: {{ .Values.targetImageName }}
    opendatahub.io/notebook-image-url: {{ .Values.gitRepository }}
    # Adjust accelerator recommendations as needed
    opendatahub.io/recommended-accelerators: '[]'
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: false
