apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: target-custom-minimal-notebook
  namespace: redhat-ods-applications
  annotations:
    opendatahub.io/notebook-image-desc: Jupyter notebook image with minimal dependencies and an extra package added 
    opendatahub.io/notebook-image-name: Minimal Python + pypdf
    opendatahub.io/notebook-image-url: https://github.com/butler54/rhoai-custom-image
spec:
  lookupPolicy:
    local: false